# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagebox.ui'
#
# Created: Tue Jun 16 17:28:15 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_imagebox(object):
    def setupUi(self, imagebox):
        imagebox.setObjectName("imagebox")
        imagebox.resize(522, 168)
        imagebox.setWindowTitle("")
        self.gridLayout = QtGui.QGridLayout(imagebox)
        self.gridLayout.setObjectName("gridLayout")
        self.picture = QtGui.QLabel(imagebox)
        self.picture.setMinimumSize(QtCore.QSize(160, 160))
        self.picture.setMaximumSize(QtCore.QSize(160, 160))
        self.picture.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.picture.setAutoFillBackground(False)
        self.picture.setStyleSheet("")
        self.picture.setTextFormat(QtCore.Qt.AutoText)
        self.picture.setScaledContents(True)
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture.setObjectName("picture")
        self.gridLayout.addWidget(self.picture, 0, 0, 3, 1)
        self.google = QtGui.QPushButton(imagebox)
        self.google.setMinimumSize(QtCore.QSize(0, 0))
        self.google.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.google.setObjectName("google")
        self.gridLayout.addWidget(self.google, 0, 1, 1, 1)
        self.source = QtGui.QLineEdit(imagebox)
        self.source.setObjectName("source")
        self.gridLayout.addWidget(self.source, 0, 2, 1, 1)
        self.attribute = QtGui.QCheckBox(imagebox)
        self.attribute.setMinimumSize(QtCore.QSize(96, 0))
        self.attribute.setMaximumSize(QtCore.QSize(96, 16777215))
        self.attribute.setObjectName("attribute")
        self.gridLayout.addWidget(self.attribute, 0, 3, 1, 1)
        self.tineye = QtGui.QPushButton(imagebox)
        self.tineye.setMinimumSize(QtCore.QSize(0, 0))
        self.tineye.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tineye.setObjectName("tineye")
        self.gridLayout.addWidget(self.tineye, 1, 1, 1, 1)
        self.status = QtGui.QComboBox(imagebox)
        self.status.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.setItemText(0, "")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.gridLayout.addWidget(self.status, 1, 2, 1, 1)
        self.remove = QtGui.QCheckBox(imagebox)
        self.remove.setObjectName("remove")
        self.gridLayout.addWidget(self.remove, 1, 3, 1, 1)
        self.notes = QtGui.QTextEdit(imagebox)
        self.notes.setObjectName("notes")
        self.gridLayout.addWidget(self.notes, 2, 1, 1, 3)
        self.list_delete = QtGui.QAction(imagebox)
        self.list_delete.setObjectName("list_delete")
        self.email = QtGui.QAction(imagebox)
        self.email.setObjectName("email")

        self.retranslateUi(imagebox)
        QtCore.QMetaObject.connectSlotsByName(imagebox)

    def retranslateUi(self, imagebox):
        self.picture.setText(QtGui.QApplication.translate("imagebox", "Loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.google.setText(QtGui.QApplication.translate("imagebox", "Google", None, QtGui.QApplication.UnicodeUTF8))
        self.attribute.setText(QtGui.QApplication.translate("imagebox", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.tineye.setText(QtGui.QApplication.translate("imagebox", "TinEye", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(1, QtGui.QApplication.translate("imagebox", "PUBLIC DOMAIN", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(2, QtGui.QApplication.translate("imagebox", "BY-SA CC", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(3, QtGui.QApplication.translate("imagebox", "BY-NC-SA CC", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(4, QtGui.QApplication.translate("imagebox", "PERMISSION GRANTED", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(5, QtGui.QApplication.translate("imagebox", "REPLACED", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(6, QtGui.QApplication.translate("imagebox", "AWAITING REPLY", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(7, QtGui.QApplication.translate("imagebox", "SOURCE UNKNOWN", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(8, QtGui.QApplication.translate("imagebox", "UNABLE TO CONTACT", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(9, QtGui.QApplication.translate("imagebox", "PERMISSION DENIED", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(10, QtGui.QApplication.translate("imagebox", "PERMANENTLY REMOVED", None, QtGui.QApplication.UnicodeUTF8))
        self.remove.setText(QtGui.QApplication.translate("imagebox", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.list_delete.setText(QtGui.QApplication.translate("imagebox", "Delete From List", None, QtGui.QApplication.UnicodeUTF8))
        self.email.setText(QtGui.QApplication.translate("imagebox", "Copy Email Text", None, QtGui.QApplication.UnicodeUTF8))

